project_id = "wftzeeggrwuwzutaiwjp"

[functions.send-contact-email]
verify_jwt = false

[functions.check-user-role]
verify_jwt = false

[functions.notify-application-status]
verify_jwt = false

[functions.label-coach]
verify_jwt = false
